name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - staging
          - production

env:
  AWS_REGION: ap-southeast-1

jobs:
  Terraform-Deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Set Environment Variables
      run: |
        echo "TF_VAR_environment=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
        echo "TF_VAR_ecs_cluster_name=${{ github.event.inputs.environment }}-cluster" >> $GITHUB_ENV
        echo "TF_VAR_ecs_task_family=${{ github.event.inputs.environment }}-task-family" >> $GITHUB_ENV
        echo "TF_VAR_ecs_service_name=${{ github.event.inputs.environment }}-service" >> $GITHUB_ENV
        echo "TF_VAR_dynamodb_table_name=${{ github.event.inputs.environment }}-dynamodb-table" >> $GITHUB_ENV
        echo "TF_VAR_container_name=${{ github.event.inputs.environment }}-container" >> $GITHUB_ENV
        echo "TF_VAR_ecr_repository=${{ github.event.inputs.environment }}-repository" >> $GITHUB_ENV

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ secrets.S3_BUCKET }}" \
          -backend-config="key=terraform/ce8-coaching-18/${{ github.event.inputs.environment }}/terraform.tfstate" \
          -backend-config="region=${{ env.AWS_REGION }}" 

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: |
        terraform plan \
          -var="environment=${{ env.TF_VAR_environment }}" \
          -var="ecs_cluster_name=${{ env.TF_VAR_ecs_cluster_name }}" \
          -var="ecs_task_family=${{ env.TF_VAR_ecs_task_family }}" \
          -var="ecs_service_name=${{ env.TF_VAR_ecs_service_name }}" \
          -var="dynamodb_table_name=${{ env.TF_VAR_dynamodb_table_name }}" \
          -var="container_name=${{ env.TF_VAR_container_name }}" \
          -var="ecr_repository=${{ env.TF_VAR_ecr_repository }}" \
          -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

    - name: Generate Outputs
      run: terraform output > tf_outputs.txt

    - name: Upload Outputs to S3
      run: |
        OUTPUT_PATH="terraform/ce8-coaching-18/${{ github.event.inputs.environment }}/tf_output"
        aws s3 cp tf_outputs.txt s3://${{ secrets.S3_BUCKET }}/${OUTPUT_PATH} --content-type text/plain
